### ISSUE TITLE
Make :Unite grep take default input pattern?

### ISSUE THREAD

**Issue by lfilho** [Shougo/unite.vim#280]
Hi,

I tried:
`nnoremap ,ug :<C-u>UniteWithCursorWord grep:.<CR>`
and also
`nnoremap ,ug :<C-u>Unite -input=testing grep:.<CR>`

in an attempt to pre-populate the Pattern string to be searched for, but didn't work.
Is it possible?

Would it be difficult to include this functionality?

Thanks!

**Comment by acornejo** [comment]
I am hitting a similar issue.

I want to start Unite with a prefilled pattern (but WITHOUT actually starting the search, so I can edit the pattern if I want). Specifically, I would like to use the cursor under the word be the suggested pattern.

UniteWIthCursorWord does not do what I need, since it performs the search right away without giving me a chance to edit the pattern.

Instead I tried this:

````map <leader>a :Unite -start-insert -no-quit -buffer-name=ag grep:.:<C-R>w<CR>```

The `<C-R>w` was supposed to insert the word under the cursor as the starting pattern. However, this didn't work either. Suggestions?

**Comment by Shougo** [comment]
```vim
nnoremap <leader>a :Unite -start-insert -no-quit -buffer-name=ag grep:.:<C-R><C-w><CR>
```

`<C-R>w` is wrong.

**Comment by acornejo** [comment]
Thanks. I've already noticed that doesn't work, but I want to know what else would start the search with the word under the cursor (and give me a chance to edit before searching)

**Comment by Shougo** [comment]
OK.  I updated.
Please use `<Plug>(unite_restart)` for the edit.

**Comment by juanpabloaj** [comment]
can I use `Unite vimgrep` with `<cword> ` ? like

    nn <silent> <leader>ug :<C-u>Unite vimgrep:**:<cword>:<CR>

**Comment by Shougo** [comment]
`nn <silent> <leader>ug :<C-u>UniteWithCursorWord vimgrep:**:<CR>`

**Comment by juanpabloaj** [comment]
@shougo when I try with you nnoremap, vim request the pattern (I use vim 7.4)

    Pattern:

**Comment by Shougo** [comment]
Oh, vimgrep does not support `-input` feature.
OK.

Please use this.

```vim
nn <silent> <leader>ug :<C-u>UniteWithCursorWord vimgrep:**:`expand('<cword>')`<CR>
```
