### ISSUE TITLE
Option to clear the prompt input when resuming.

### ISSUE THREAD

**Issue by sbutts** [Shougo/unite.vim#823]
This request is similar to #736, but besides just restoring the cursor to the prompt line I'd also like to clear the previous input.
For example, if I wanted to open a file named foobar I'd search for it using file_rec and open it. But if I wanted to open a different file using the resume option would restore the file_rec buffer but foobar would still be on the input line.

I tried adding <C-u> to the end of the Unite map line but that didn't clear the input like I thought it would.
nnoremap [unite_key]f :<C-u>Unite -resume -short-source-names -buffer-name=files buffer file_rec/async<CR><C-u>

**Comment by Shougo** [comment]
`:Unite -resume -short-source-names -buffer-name=files -input= buffer file_rec/async`

**Comment by sbutts** [comment]
Yeah I tried that before and it doesn't work. Adding -input= seems to delete one character from the input line but not the entire line.

**Comment by Shougo** [comment]
OK.  I get it.  I will fix it.

**Comment by sbutts** [comment]
Thanks! It works great now.

**Comment by smackesey** [comment]
I am trying something similar but it isn't working for me. I'm executing `Unite -resume -input= SOURCES...` from within a Unite buffer, and it doesn't clear the input (it seems to do nothing). It does reset the input if I pass a different string though.

**Comment by Shougo** [comment]
@smackesey I have tested it and it works.
Have you read the issue template?
Please create the new issue with the minimal vimrc.

**Comment by smackesey** [comment]
I recognize that this repo is no longer maintained, but I am putting a workaround here for anyone frustrated by this issue. The problem is that:

    Unite -resume -input= SOURCES...

only works if the sources are the *same* as for the previous Unite buffer. I tracked this behavior to the function `unite#start#standard`. If the sources are not the same, then no special resume behavior is used. This leads to a failure to clear the prompt when passing `-input=`. You can replicate this by running:

    Unite buffer

Type some characters in the prompt, then:

    Unite -input= function

You should see that the prompt was not cleared. This is clearly a bug, as passing `input=` should clear the prompt.

In any case, the workaround is to run these two lines immediately after the second `Unite` call:

      call unite#mappings#narrowing('')
      call unite#redraw()

This will clear the prompt (the code was taken from `unite#start#resume`).

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/823#issuecomment-373231517

Have you read my previous comment?
I don't add new feature to unite.vim.

But I can fix the problem.

I don't reproduce the problem again.
If you ignore my comment, I ignore your report.

**Comment by Shougo** [comment]
Sorry.  I have not reproduce your problem.

I have tested

```vim
Unite -input=foo buffer
Unite -input= -resume file
```

The input will be cleared.

**Comment by Shougo** [comment]
Note:  I have tested the minimal vimrc.

**Comment by Shougo** [comment]
> Provide a minimal .vimrc with less than 50 lines (Required!)

The minimal vimrc is really correct???

**Comment by Shougo** [comment]
Please use 
vim -Nu minvimrc
instead.

The errors are occurred.

**Comment by Shougo** [comment]
Reproduced

**Comment by Shougo** [comment]
Fixed.
