### ISSUE TITLE
-resume + -start-insert behaves badly

### ISSUE THREAD

**Issue by kballard** [Shougo/unite.vim#825]
When using both `-resume` and `-start-insert`, Unite restores the cursor, then switches to insert mode where the cursor is instead of moving the cursor to the prompt. This causes various bad behavior, including scrolling the window sideways, and often joining that line with the next line.

Adding `-no-restore` seems to work around this issue, but that flag shouldn't be necessary.

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/439

It is feature and option "-no-restore" is available.

**Comment by kballard** [comment]
Did you actually try it? The way it behaves is most definitely a bug.

**Comment by Shougo** [comment]
OK.  Please read issue template and reproduce ways.
https://github.com/Shougo/unite.vim/issues/584

If you report it, I will try it.

**Comment by kballard** [comment]
* Problems summary

When using `-resume` and `-start-insert` together, Unite doesn't set up
buffer-local insert mappings early enough, causing any pending keys (such as
those from maps) to execute with the global insert mapping. This can cause the
buffer to get into an invalid state.

This ends up being pretty easy to reproduce using a common type of mapping that
invokes `<C-u>` after bringing up Unite, such as

```vim
nnoremap <silent> <leader>f :<C-u>Unite -resume -start-insert file_rec/async:!<cr><C-u>
```

With this type of mapping, if the cursor was left on one of the buffer lines
instead of at the prompt, resuming Unite will invoke the global imap for
`<C-u>`. If `'backspace'` is set to `start,eol` then this will cause the
selected row to be joined with the previous row, which is not at all correct.

* Expected

Any keystrokes after the mapping, such as `<C-u>`, should execute with the same
buffer-local mappings that are setup by the time control returns to the user. Or
more generally, putting `<C-u>` at the end of the mapping should behave as
expected and clear the input.

* Environment Information
 * OS: OS X 10.10.1 (14B25)
 * Vim version: Vim 7.4.258

* Minimal vimrc less than 50 lines

```
set nocompatible
set runtimepath+=~/.vim/neobundle/unite.vim

set backspace=eol,start

nnoremap <silent> ,s :<C-u>Unite -resume -start-insert source<cr><C-u>
```

* Reproducable ways from Vim starting

 1. Startup vim: `vim -u minimal.vimrc`
 2. Press `,s`
 3. Press `<esc>` to exit insert mode, and `j` 3 times to select the row
    "change".
 4. Press `q` to exit Unite
 5. Press `,s` to bring Unite back

At this point the cursor is at the very right edge of the previous row
"buffer_tab", which has been joined with the row "change" so that row no
longer exists in the list, and the entire window is scrolled over partially.

* Screen shot (if possible)

![unite bug](https://cloud.githubusercontent.com/assets/714/5809783/776a8b34-9ff1-11e4-9d43-5d602d9b86dd.gif)

**Comment by Shougo** [comment]
OK.  I get it.

**Comment by Shougo** [comment]
@kballard To clear input, you should use `:Unite -resume -input=`.

**Comment by petobens** [comment]
With the following minimal vimrc the cursor is not restored in the Unite buffer (this can be seen in the Gif)

    set nocompatible

    let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
    let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

    set runtimepath+=$DOTVIM/bundle/unite

    call unite#custom#profile('default', 'context', { 'start_insert' : 1 })

    nnoremap <silent> ,tl :Unite -silent -auto-resize -auto-highlight
                \ vimgrep:%:\\CTODO\:<CR>
    nnoremap <silent> ,ur :UniteResume -force-redraw -immediately <CR>

    " TODO: first
    " TODO: second
    " TODO: third

If press `,tl`, then move to the third candidate, then exit the Unite buffer and finally press `,ur` instead of restoring the cursor at the third candidate the cursor jumps to the prompt. 

![blah](https://cloud.githubusercontent.com/assets/2583971/5958750/c5df05f8-a7a6-11e4-87f5-4883239463f7.gif)

**Comment by Shougo** [comment]
Yes.  It is intended behavior.  You can talk to @kballard for the problem.

**Comment by kballard** [comment]
@petobens Your custom profile includes `start_insert: 1`. If you're in insert mode, you should expect to be at the prompt, no? Just as if you'd pressed `i` after resuming without `start_insert`.

**Comment by petobens** [comment]
@kballard thanks for the explanation. I've added the `no-start-insert` flago to `:UniteResume` mapping.

**Comment by seletskiy** [comment]
@Shougo: I've never seen bug described by @kballard, but it was very useful to have cursor restored at previous position on resume command (e.g. in cases where you need to go from file to file). Now it's impossible to do and very inconvinient (as far as I can see cursor restoration code was just deleted).

Maybe it's a better solution to have some kind of flag like `-restore-cursor` to solve problems for different cases?

**Comment by Shougo** [comment]
You can talk to @kballard.
It is not bug.  But it is wired behavior.

**Comment by seletskiy** [comment]
@Shougo What it will solve? @kballard did not modify the code and discussion with him will not resolve into anything. I'm aware of his point and understand it completely, but I didn't get why it's intended behaviour. Removed block of code which cause bug for him was an useful feature for me.

Consider following situation (before eaf0cbb):
* I've always started Unite with start_insert option, because I always need to narrow my results;
* Then, after messing with some file, I can invoke UniteResume and type Up or Down for selecting next or previous file;
* If, instead, I want to select entirely different file, I can just start typing or C-W'ing because I've already in insert mode.

Now:
* I've starting Unite as before using start_insert;
* Invoking UniteResume with either start_insert and have incorrect file chosen (not that was chosen in first invokation) or either without start_insert and have valid file chosen, but then I need to keep in mind, that _every_ invokation of Unite is launched in insert mode except UniteResume.

I'll glad to make PR which will introduce flag `-restore-cursor`, so both of my and @kballard cases will be satisfied. Just let me know.

**Comment by kballard** [comment]
Honestly, I think the best solution here is to make it so moving to the prompt does not move selection to the first file in the list if the use has not actually edited the prompt in any way. That way you can restore everything, including `start_insert`, but have the highlighted item continue to be the item that was last selected. That way actioning the item, or exiting Insert mode, will leave you on the same item that was last selected.

This also makes more sense to me as just general behavior. If I start arrowing down the list, then hit `i` to go into Insert mode, and change my mind and hit `Esc`, I'd rather be at the same item I had selected before, instead of having the selection always jump back to the first item in the list. If I edit the prompt in any fashion then I'd expect it to jump back to the top, but without any editing, it shouldn't move my selection for me.

**Comment by seletskiy** [comment]
@kballard: Completely agree with you.

**Comment by Shougo** [comment]
> This also makes more sense to me as just general behavior. If I start arrowing down the list, then hit i to go into Insert mode, and change my mind and hit Esc, I'd rather be at the same item I had selected before, instead of having the selection always jump back to the first item in the list. If I edit the prompt in any fashion then I'd expect it to jump back to the top, but without any editing, it shouldn't move my selection for me.

Yes.  It is good solution.
But please care backward compatibility.

This feature is available your Vim is greater or equal than Vim 7.3.867.
I can implement this feature.  But if your Vim is less than Vim 7.3.867, you cannot move to the prompt line.

**Comment by kballard** [comment]
> I can implement this feature. But if your Vim is less than Vim 7.3.867, you cannot move to the prompt line.

Oh really? Huh. Well, I'm using 7.4.258 at the moment, so that's fine with me. Having it retain the current behavior on versions older than 7.3.867 would be fine (since they aren't losing anything).

**Comment by kovetskiy** [comment]
@Shougo okay, when you can implement this feature? It's really necessary.

**Comment by Shougo** [comment]
I can implement this feature.  But it is not easy.
I must rewrite insert mode mappings.  Not just add the feature.

**Comment by Shougo** [comment]
Implemented it.

**Comment by kovetskiy** [comment]
@Shougo thank you!

**Comment by petobens** [comment]
@Shougo , something doen't work for me after your last commit. Consider the following minimal vimrc:
```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/unite

call unite#custom#profile('default', 'context', { 'start_insert' : 1 })

nnoremap <silent> ,tl :Unite -silent -auto-resize -auto-highlight
            \ vimgrep:%:\\CTODO\:<CR>
nnoremap <silent> ,ur :UniteResume -force-redraw -immediately <CR>

" TODO: first
" TODO: second
" TODO: third
```

As it can be seen in the GIF, press ,tl, then select the second candidate, then press `,ur`  and when the resume buffer opens select once again the second candidate. You will see that Unite instead of jumping again to the second candidate in the vimrc min file it jumps to it inside the Unite resume buffer. 
![rec](https://cloud.githubusercontent.com/assets/2583971/7441154/d326ac9e-f0b1-11e4-98b7-f6659b21e785.gif)

**Comment by Shougo** [comment]
> nnoremap <silent> ,ur :UniteResume -force-redraw -immediately <CR>

Please don't use `-force-redraw` option for it.
Because, `:Unite vimgrep:%` executes vimgrep for unite buffer.
It is your not intended behavior.

**Comment by petobens** [comment]
@Shougo if I don't use `force-redraw` then I have the same problem as in #804 .

**Comment by Shougo** [comment]
@petobens Fixed.  Please update unite.vim.

**Comment by petobens** [comment]
@Shougo. Thank you! There is one minor problem. When I input some character in the prompt and then use `Unite resume` the cursor is one character to the left (instead of being at the end of the prompt). Please see the gif below:

![character](https://cloud.githubusercontent.com/assets/2583971/7453802/7fe89266-f243-11e4-9ba4-136b36b1fbd4.gif)

**Comment by Shougo** [comment]
Fixed the problem.
Please update unite.vim.

**Comment by petobens** [comment]
Thank you!
