### ISSUE TITLE
Question: how is this table of content generated with CSS?

### ISSUE THREAD

**Issue by roylez** [Shougo/unite.vim#922]
I just stumble on this [CSS file](https://gist.github.com/roylez/186deb8556cf07b1040f) which contains a table of content in the beginning. Unite-outline happens to pick up the TOC and allows me to jump to each section correctly (Although Section 1 is somehow missing in the outline view). To my eyes, these sections are defined merely in comments and looks like nothing special.

My question is, how is this TOC defined? Is it a feature only for CSS syntax, or something common that could be used in other file types, like SASS, html, ruby and etc?

Thank you very much.

**Comment by Shougo** [comment]
It is unite-ouline issue.

https://github.com/Shougo/unite-outline/issues

But I don't know about it(I just maintain it instead of @h1mesuke )

You can change the routine and pull request is wellcome.
https://github.com/Shougo/unite-outline/blob/master/autoload/unite/sources/outline/defaults/css.vim
