### ISSUE TITLE
Path separator bug on Windows

### ISSUE THREAD

**Issue by BohrShaw** [Shougo/unite.vim#979]
With `shellslash` reset, `:Unite file:C:\Users\Bohr\.vim` finds files in $HOME which I think is a fallback when the path is not found.

**Comment by Shougo** [comment]
https://github.com/Shougo/unite.vim/issues/584

**Comment by BohrShaw** [comment]
Sorry for the lack of clarity! Here's how to reproduce:

In the `$HOME` directory, issue command `gvim -Nu NORC --cmd 'set rtp+=~/.vim/bundle/unite.vim' -c 'Unite file:C:\Users\Bohr\.vim`, I get files in $HOME and the status line of the Unite window shows `file:C:UsersBohr.vim ...`.

It seems the path separator `\` is not escaped properly.

**Comment by poppyschmo** [comment]
I've noticed the same behavior when calling `:Unite file:c:\not\home\dir`. Didn't really bother me, though, since default `'wildmode'` completion doesn't work (I think it's confused by the `file:` prefix). At least you can always use forward slashes, even with `:set shellslash&`.

`C:\Users\Uname>gvim -Nu c:\vim74\vimrc_example.vim --cmd "set rtp+=~/vimfiles/bundle/unite.vim" -c "Unite file:C:/Users/Uname/Documents"`

It seems `UniteWithInputDirectory` also needs forward slashes, though wildmode completion does work at the initial input prompt, but only with `'shellslash'` on. It also appends a trailing slash, I think.

Grep, to my surprise, behaves much better with backslashes.

`C:\Users\Uname>gvim -Nu c:\vim74\vimrc_example.vim --cmd "set rtp+=~/vimfiles/bundle/unite.vim,~/vim files/bundle/vimproc"`

At the input prompt, if you type a full path or add a relative path after the dot: `target: .\go\here`, it wildmode completes and gracefully converts to forward slashes before searching.

**Comment by BohrShaw** [comment]
I'll just `set shellslash` for certain reasons all leading to better User Experience.

Besides,

- [vimproc](https://github.com/shougo/vimproc.vim) is also not fully tested against 'shellslash'.
    - e.g. a broken command after `set noshellslash`: `:VimProcBang git log origin/master`
- [vim-gnupg](https://github.com/jamessan/vim-gnupg) breaks after `set shellslash`.
    - I've fired an issue: https://github.com/jamessan/vim-gnupg/issues/41
- [vim-fugitive](https://github.com/tpope/vim-fugitive) deals with 'shellslash' very well.

**Comment by Shougo** [comment]
Are, I get it.
You must esccape "\" in the command line.

```vim
:Unite file:C:\\Users\\Bohr\\.vim
```
